BMongo1/Areas/Admin/Controllers/CategoriesAdminController.cs
using BMongo1.Controllers;
using BMongo1.Models;
using BMongo1.Models.BusinessModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Xml.Linq;

namespace BMongo1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriesAdminController : Controller
    {
        IRepositoryAccount repositoryaccount;
        IRepositoryCategory repositorycategory;
        IRepositoryCart repositorycart;
        IRepositoryProduct repositoryproduct;

        public CategoriesAdminController(IRepositoryAccount repositoryaccount, IRepositoryCategory repositorycategory, IRepositoryCart repositorycart, IRepositoryProduct repositoryproduct, ILogger<HomeController> logger)
        {
            this.repositoryaccount = repositoryaccount;
            this.repositorycategory = repositorycategory;
            this.repositorycart = repositorycart;
            this.repositoryproduct = repositoryproduct;
        }
        public IActionResult Index(string name, int page = 1)
        {
            page = page < 1 ? 1 : page;
            if (string.IsNullOrEmpty(name))
            {
                long totalpage;
                var data = repositorycategory.Paging(page, 4, out totalpage);
                ViewBag.totalpage = totalpage;
                ViewBag.page = page;
                return View(data);
            }
            else
            {
                long totalpage;
                var data = repositorycategory.SearchPaging(name, page, 4, out totalpage);
                ViewBag.totalpage = totalpage;
                ViewBag.page = page;
                ViewBag.name = name;
                return View(data);
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/CategoriesAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            TempData["Message"] = "";
            var check = repositorycategory.GetAll();
            var err = true;
            foreach (var c in check)
            {
                if (category.CategoryName == c.CategoryName)
                {
                    ViewBag.errorName = "The category name already exists";
                    err = false;
                }
            }
            if (err == false)
            {
                return View();
            }


            if (ModelState.IsValid)
            {
                var categories = repositorycategory.Insert(category);
                TempData["Message"] = "New category added successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: Admin/CategoriesAdmin/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = repositorycategory.GetById(id);

            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/CategoriesAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Category category)
        {
            TempData["Message"] = "";
            var check = repositorycategory.GetAll();
            var err = true;
            foreach (var c in check)
            {
                if (category.CategoryName == c.CategoryName)
                {
                    ViewBag.errorName = "The category name already exists";
                    err = false;
                }

            }
            if (err == false)
            {
                return View();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    var categories = repositorycategory.Update(category);
                    TempData["Message"] = "Category update successful";
                }
                catch (Exception)
                {

                    return NotFound();

                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/CategoriesAdmin/Delete/?
        public IActionResult Delete(int id)
        {
            var pro = repositoryproduct.GetAll();
            int check = 0;
            foreach (var b in pro)
            {
                if (b.CategoryId == id)
                {
                    check++;
                    TempData["MessageError"] = "There are products in this category!";
                }

            }
            if (check == 0)
            {
                var category = repositorycategory.Delete(id);

                TempData["Message"] = "Category deletion successful";
            }
            return RedirectToAction(nameof(Index));
        }


    }
}

BMongo1/Areas/Admin/Views/CategoriesAdmin/Create.cshtml
@model BMongo1.Models.Category

@{
    ViewData["Title"] = "Category Create Page";
}

<div class="row mb-2">
    <div class="col-sm-6">
        <h1 class="m-0">Category Create</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="HomeAdmin" asp-action="Index">Home Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="CategoriesAdmin" asp-action="Index">Category management</a></li>
            <li class="breadcrumb-item active">Category Create</li>
        </ol>
    </div>
</div>
<hr />
<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="CategoryName" class="control-label"></label>
        <input asp-for="CategoryName" class="form-control" />
        <span asp-validation-for="CategoryName" class="text-danger"></span>
        <span class="text-danger">@ViewBag.errorName</span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BMongo1/Areas/Admin/Views/CategoriesAdmin/Edit.cshtml
@model BMongo1.Models.Category

@{
    ViewData["Title"] = "Category Edit Page";
}

<div class="row mb-2">
    <div class="col-sm-6">
        <h1 class="m-0">Category Edit</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="HomeAdmin" asp-action="Index">Home Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="CategoriesAdmin" asp-action="Index">Category management</a></li>
            <li class="breadcrumb-item active">Category Edit</li>
        </ol>
    </div>
</div>
<hr />
<form asp-controller="CategoriesAdmin" asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="_id" class="control-label"></label>
        <input class="form-control" readonly asp-for="_id" />
        
    </div>
    <div class="form-group">
        <label asp-for="CategoryName" class="control-label"></label>
        <input asp-for="CategoryName" class="form-control" />
        <span asp-validation-for="CategoryName" class="text-danger"></span>
        <span class="text-danger">@ViewBag.errorName</span>
    </div>

    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BMongo1/Areas/Admin/Views/CategoriesAdmin/Index.cshtml
@model IEnumerable<BMongo1.Models.Category>

@{
    ViewData["Title"] = "Category list Page";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row mb-2">
    <div class="col-sm-6">
        <h1 class="m-0">Category list</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="HomeAdmin" asp-action="Index">Home Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="CategoriesAdmin" asp-action="Index">Category management</a></li>
            <li class="breadcrumb-item active">Category list</li>
        </ol>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-8 offset-md-2">
        <form action="#">
            <div class="input-group">
                <input type="search" name="name" class="form-control form-control-lg" placeholder="Enter a name to search...">
                <div class="input-group-append">
                    <button type="submit" class="btn btn-lg btn-default">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <a asp-action="Create" class="btn btn-primary pt-2"><i class="fas fa-plus"></i> Create</a>
</div>
<h5 class="my-3">
    <b class="text-success">@TempData["Message"]</b>
    <b class="text-danger">@TempData["MessageError"]</b>
</h5>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault()._id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().CategoryName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item._id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryName)
                </td>
                <td>
                    <a asp-controller="CategoriesAdmin" class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item._id">Edit</a> |
                    <a asp-controller="CategoriesAdmin" asp-action="Delete" class="btn btn-outline-danger" asp-route-id="@item._id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="card-footer clearfix">
    <ul class="pagination pagination-sm m-0 float-right">
        @for (int i = 1; i <= ViewBag.totalpage; i++)
        {
            if (i == (int)ViewBag.page)
            {
                <li class="page-item"><span class="page-link">@i</span></li>

            }
            else if (ViewBag.name != null)
            {
                <li class="page-item">
                    <a class="page-link" href="?page=@i&name=@ViewBag.name">
                        @i
                    </a>
                </li>
            }
            else

            {
                <li class="page-item"><a class="page-link" href="?page=@i">@i</a></li>

            }
        }
    </ul>
</div>