BMongo1/Areas/Admin/Controllers/ProductsAdminController.cs
using BMongo1.Controllers;
using BMongo1.Models;
using BMongo1.Models.BusinessModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Xml.Linq;

namespace BMongo1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductsAdminController : Controller
    {
        IRepositoryAccount repositoryaccount;
        IRepositoryCategory repositorycategory;
        IRepositoryCart repositorycart;
        IRepositoryProduct repositoryproduct;

        public ProductsAdminController(IRepositoryAccount repositoryaccount, IRepositoryCategory repositorycategory, IRepositoryCart repositorycart, IRepositoryProduct repositoryproduct, ILogger<HomeController> logger)
        {
            this.repositoryaccount = repositoryaccount;
            this.repositorycategory = repositorycategory;
            this.repositorycart = repositorycart;
            this.repositoryproduct = repositoryproduct;
        }
        public IActionResult Index(string name, int page = 1)
        {
            page = page < 1 ? 1 : page;
            if (string.IsNullOrEmpty(name))
            {
                long totalpage;
                var data = repositoryproduct.Paging(page, 4, out totalpage);
                ViewBag.totalpage = totalpage;
                ViewBag.page = page;
                return View(data);
            }
            else
            {
                long totalpage;
                var data = repositoryproduct.SearchPaging(name, page, 4, out totalpage);
                ViewBag.totalpage = totalpage;
                ViewBag.page = page;
                ViewBag.name = name;
                return View(data);
            }
        }

        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(repositorycategory.GetAll(), "_id", "CategoryName");
            return View();
        }

        // POST: Admin/ProductsAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            TempData["Message"] = "";

            var check = repositoryproduct.GetById(product._id);

            if (check != null)
            {
                ViewBag.errorId = "The Product ID already exists";
                ViewData["CategoryId"] = new SelectList(repositorycategory.GetAll(), "_id", "CategoryName");
                return View();
            }


            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;

                if (files.Count() > 0 && files[0].Length > 0)
                {
                    var file = files[0];
                    var FileName = file.FileName;
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images", FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        file.CopyTo(stream);
                        product.ProductImage = FileName;
                    }
                }
                var products = repositoryproduct.Insert(product);
                TempData["Message"] = "New product added successfully";
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(repositorycategory.GetAll(), "_id", "CategoryName");
            return View(product);
        }

        // GET: Admin/ProductsAdmin/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = repositoryproduct.GetById(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(repositorycategory.GetAll(), "_id", "CategoryName");
            return View(product);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Product product, string? Image)
        {
            TempData["Message"] = "";


            try
            {
                var files = HttpContext.Request.Form.Files;

                if (files.Count() > 0 && files[0].Length > 0)
                {
                    var file = files[0];
                    var FileName = file.FileName;
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images", FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        file.CopyTo(stream);
                        product.ProductImage = FileName;
                    }
                }
                else
                {
                    product.ProductImage = Image;
                }

                repositoryproduct.Update(product);
                TempData["Message"] = "Product update successful";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {


                ViewData["CategoryId"] = new SelectList(repositorycategory.GetAll(), "_id", "CategoryName");
                return View(product);

            }


        }

        // GET: Admin/ProductsAdmin/Delete/5
        public IActionResult Delete(string id)
        {
            repositoryproduct.Delete(id);
            TempData["Message"] = "Product deletion successful";
            return RedirectToAction(nameof(Index));
        }

    }
}

BMongo1/Areas/Admin/Views/ProductsAdmin/Create.cshtml
@model BMongo1.Models.Product

@{
    ViewData["Title"] = "Product Edit Page";
}

<div class="row mb-2">
    <div class="col-sm-6">
        <h1 class="m-0">Product Create</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="HomeAdmin" asp-action="Index">Home Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="ProductsAdmin" asp-action="Index">Product management</a></li>
            <li class="breadcrumb-item active">Product Create</li>
        </ol>
    </div>
</div>
<hr />
<form asp-action="Create" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="_id" class="control-label"></label>
        <input asp-for="_id" class="form-control" />
        <span asp-validation-for="_id" class="text-danger"></span>
        <span class="text-danger">@ViewBag.errorId</span>
    </div>
    <div class="form-group">
        <label asp-for="ProductName" class="control-label"></label>
        <input asp-for="ProductName" class="form-control" />
        <span asp-validation-for="ProductName" class="text-danger"></span>
        <span class="text-danger">@ViewBag.error</span>
    </div>
    <div class="form-group">
        <label asp-for="Price" class="control-label"></label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" class="form-control" rows="6"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ProductImage" class="control-label"></label>
        <input asp-for="ProductImage" type="file" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="ProductStatus" class="control-label"></label>
        <select asp-for="ProductStatus" class="form-control">
            <option value="In stock">In stock</option>
            <option value="Out of stock">Out of stock</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="CategoryId" class="control-label"></label>
        <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BMongo1/Areas/Admin/Views/ProductsAdmin/Edit.cshtml
@model BMongo1.Models.Product

@{
    ViewData["Title"] = "Product Edit Page";
}

<div class="row mb-2">
    <div class="col-sm-6">
        <h1 class="m-0">Product Edit</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="HomeAdmin" asp-action="Index">Home Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="ProductsAdmin" asp-action="Index">Product management</a></li>
            <li class="breadcrumb-item active">Product Edit</li>
        </ol>
    </div>
</div>
<hr />
<form asp-action="Edit" asp-controller="ProductsAdmin" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="_id" class="control-label"></label>
        <input class="form-control" readonly asp-for="_id" />
    </div>
    <div class="form-group">
        <label asp-for="ProductName" class="control-label"></label>
        <input asp-for="ProductName" class="form-control" />
        <span asp-validation-for="ProductName" class="text-danger"></span>
        <span class="text-danger">@ViewBag.error</span>
    </div>
    <div class="form-group">
        <label asp-for="Price" class="control-label"></label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" class="form-control" rows="6"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-6">
                <img src="~/Images/@Model.ProductImage" width="25%" height="100" />
            </div>
            <div class="col-6">
                <label asp-for="ProductImage" class="control-label"></label>
                <input asp-for="ProductImage" type="file" class="form-control mb-2" />
                <input name="Image" class="form-control mb-2" type="hidden" value="@Model.ProductImage" />
            </div>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="ProductStatus" class="control-label"></label>
        <select asp-for="ProductStatus" class="form-control">
            <option value="In stock">In stock</option>
            <option value="Out of stock">Out of stock</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="CategoryId" class="control-label"></label>
        <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BMongo1/Areas/Admin/Views/ProductsAdmin/Index.cshtml
@model IEnumerable<BMongo1.Models.Product>
@{
    ViewData["Title"] = "Product list Page";
}

<div class="row mb-2">
    <div class="col-sm-6">
        <h1 class="m-0">Product list</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="HomeAdmin" asp-action="Index">Home Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="ProductsAdmin" asp-action="Index">Product management</a></li>
            <li class="breadcrumb-item active">Product list</li>
        </ol>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-8 offset-md-2">
        <form action="#">
            <div class="input-group">
                <input type="search" name="name" class="form-control form-control-lg" placeholder="Enter a name to search...">
                <div class="input-group-append">
                    <button type="submit" class="btn btn-lg btn-default">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <a asp-action="Create" asp-controller="ProductsAdmin" class="btn btn-primary pt-2"><i class="fas fa-plus"></i> Create</a>
</div>
<h5 class="my-3">
    <b class="text-success">@TempData["Message"]</b>
    <b class="text-danger">@TempData["MessageError"]</b>
</h5>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault()._id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().ProductImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().ProductStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().CategoryId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item._id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <img src="~/Images/@item.ProductImage" width="100%" height="50" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryId)
                </td>
                <td>
                    <a asp-action="Edit" class="btn btn-outline-primary" asp-route-id="@item._id">Edit</a>

                    <a asp-action="Delete" class="btn btn-outline-danger" asp-route-id="@item._id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="card-footer clearfix">
    <ul class="pagination pagination-sm m-0 float-right">
        @for (int i = 1; i <= ViewBag.totalpage; i++)
        {
            if (i == (int)ViewBag.page)
            {
                <li class="page-item"><span class="page-link">@i</span></li>

            }
            else if (ViewBag.name != null)
            {
                <li class="page-item">
                    <a class="page-link" href="?page=@i&name=@ViewBag.name">
                        @i
                    </a>
                </li>
            }
            else

            {
                <li class="page-item"><a class="page-link" href="?page=@i">@i</a></li>

            }
        }
    </ul>
</div>