BMongo1/Areas/Admin/Controllers/OrdersAdminController.cs
using BMongo1.Controllers;
using BMongo1.Models;
using BMongo1.Models.BusinessModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BMongo1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrdersAdminController : Base1Controller
    {
        IRepositoryAccount repositoryaccount;
        IRepositoryCategory repositorycategory;
        IRepositoryCart repositorycart;
        IRepositoryProduct repositoryproduct;
        IRepositoryOrder repositoryorder;
        IRepositoryOrderDetail repositoryorderoetail;

        public OrdersAdminController(IRepositoryAccount repositoryaccount, IRepositoryCategory repositorycategory, IRepositoryCart repositorycart, IRepositoryProduct repositoryproduct, IRepositoryOrder repositoryorder, IRepositoryOrderDetail repositoryorderoetail)
        {
            this.repositoryaccount = repositoryaccount;
            this.repositorycategory = repositorycategory;
            this.repositorycart = repositorycart;
            this.repositoryproduct = repositoryproduct;
            this.repositoryorder = repositoryorder;
            this.repositoryorderoetail = repositoryorderoetail;
        }
        public IActionResult Index()
        {
            var order = repositoryorder.GetAll();
            return View(order);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Orders orders)
        {

            try
            {
                repositoryorder.Update(orders);
            }
            catch (Exception)
            {
                return NotFound();

            }
            return RedirectToAction(nameof(Index));

        }

    }
}

BMongo1/Areas/Admin/Views/OrdersAdmin/Index.cshtml
@model IEnumerable<BMongo1.Models.Orders>

@{
    ViewData["Title"] = "Order";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Order</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ReceiverName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReceiverPhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReceiverAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Note)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderStatus)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <form asp-area="Admin" asp-action="Edit" asp-controller="OrdersAdmin" method="post">
            <tr>
                <td>
                        @Html.DisplayFor(modelItem => item.ReceiverName)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.ReceiverPhone)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.ReceiverAddress)
                </td>
                    @if (item.Note == null || item.Note == "")
                    {
                    <td>Not Note</td>

                    }
                    else
                    {
                    <td>@Html.DisplayFor(modelItem => item.Note)</td>

                    }

                <td>
                        @Html.DisplayFor(modelItem => item.OrderDate)
                </td>
                <td>
                        @if (item.OrderStatus == "Confirming")
                        {

                        <select name="OrderStatus" class="form-control">
                            <option value="Confirming">Confirming</option>
                            <option value="Order confirmed">Order confirmed</option>
                            <option value="Received the goods">Received the goods</option>
                            <option value="Order canceled">Order canceled</option>
                        </select>
                        }
                        else if (item.OrderStatus == "Order confirmed")
                        {
                        <select name="OrderStatus" class="form-control">
                            <option value="Order confirmed">Order confirmed</option>
                            <option value="Received the goods">Received the goods</option>
                            <option value="Order canceled">Order canceled</option>
                        </select>
                        }
                        else if (item.OrderStatus == "Received the goods")
                        {
                        <b>Received the goods</b>
                        }
                        else if (item.OrderStatus == "Order canceled")
                        {
                        <b>Order canceled</b>
                        }
                </td>

                <input type="hidden" name="_id" value="@item._id" />
                <input type="hidden" name="ReceiverName" value="@item.ReceiverName" />
                <input type="hidden" name="ReceiverPhone" value="@item.ReceiverPhone" />
                <input type="hidden" name="ReceiverAddress" value="@item.ReceiverAddress" />
                <input type="hidden" name="Note" value="@item.Note" />
                <input type="hidden" name="OrderDate" value="@item.OrderDate" />
                <input type="hidden" name="AccountId" value="@item.AccountId" />

                    @if (item.OrderStatus == "Received the goods" || item.OrderStatus == "Order canceled")
                    {
                    <td><p class="btn btn-primary">Save</p>| <a asp-action="Index" asp-controller="OrderDetailsAdmin" asp-route-id="@item._id" class="btn btn-primary"> Details</a> </td>
                    }
                    else
                    {
                    <td><input type="submit" value="Save" class="btn btn-primary" />| <a asp-action="Index" asp-controller="OrderDetailsAdmin" asp-route-id="@item._id" class="btn btn-primary"> Details</a> </td>
                    }
            </tr>
            </form>
        }
    </tbody>
</table>