BMongo1/Models/ModelsViews/OrdersViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace BMongo1.Models.ModelsViews
{
    public class OrdersViewModel
    {
        public int _id { get; set; }
        public string? ReceiverName { get; set; }
        public string? ReceiverPhone { get; set; }
        public string? ReceiverAddress { get; set; }
        public string? Note { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public string? OrderDate { get; set; }
        public string? OrderStatus { get; set; }
        public int? AccountId { get; set; }
        public string? Phone { get; set; }
        public string? FullName { get; set; }
        public string? Address { get; set; }
    }
}

BMongo1/Models/Orders.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace BMongo1.Models
{
    public class Orders
    {
        
        [Column("OrdersId")]
        [Display(Name = "Orders code")]
        public int _id { get; set; }

        [Column("ReceiverName")]
        [Display(Name = "Receiver name")]
        [Required(ErrorMessage = "Receiver name cannot be blank")]
        public string? ReceiverName { get; set; }

        [Column("ReceiverPhone")]
        [Display(Name = "Receiver phone")]
        [Required(ErrorMessage = "Receiver phone can not be left blank")]
        [MinLength(10, ErrorMessage = "Receiver phone must have at least 10 digits")]
        [StringLength(10)]
        [Phone(ErrorMessage = "Receiver phone format is incorrect")]
        public string? ReceiverPhone { get; set; }

        [Column("ReceiverAddress")]
        [Display(Name = "Receiver address")]
        [Required(ErrorMessage = "Receiver address be left blank")]
        public string? ReceiverAddress { get; set; }

        [Column("Note")]
        [Display(Name = "Note")]
        public string? Note { get; set; }

        [Column("OrderDate")]
        [Display(Name = "Order date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public string? OrderDate { get; set; }

        [Column("OrderStatus")]
        [Display(Name = "Order Status")]
        public string? OrderStatus { get; set; }

        [Column("AccountId")]
        [Display(Name = "Account")]
        public int? AccountId { get; set; }
    }
}

BMongo1/Controllers/CartController.cs
using BMongo1.Models;
using BMongo1.Models.BusinessModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BMongo1.Controllers
{
    public class CartController : BaseController
    {
        IRepositoryAccount repositoryaccount;
        IRepositoryCategory repositorycategory;
        IRepositoryCart repositorycart;
        IRepositoryProduct repositoryproduct;

        public CartController(IRepositoryAccount repositoryaccount, IRepositoryCategory repositorycategory, IRepositoryCart repositorycart, IRepositoryProduct repositoryproduct)
        {
            this.repositoryaccount = repositoryaccount;
            this.repositorycategory = repositorycategory;
            this.repositorycart = repositorycart;
            this.repositoryproduct = repositoryproduct;
        }

        public async Task<IActionResult> Index()
        {

            var cart = repositorycart.GetForeignKey((int)HttpContext.Session.GetInt32("LoginId"));
            int c = 0;
            Int32 a = 0;
            foreach (var item in cart)
            {
                if (item.AccountId == HttpContext.Session.GetInt32("LoginId"))
                {
                    c++;
                    ViewData["Number_Pro"] = c;
                    a += (Int32)item.TotalPrice;
                    ViewData["Total_Cart"] = a.ToString("#,##0 $");
                    TempData["cart"] = "";
                }
            }
            if (cart == null)
            {
                TempData["cart"] = "123";
            }
            //var sem3DBContext = _context.Carts.Include(a => a.Account).Include(p => p.Product);
            return View(cart);
        }

        // POST: Cart/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Cart cart)
        {
            cart.TotalPrice *= cart.Quantity;

            if (cart.Quantity < 1)
            {
                cart.Quantity = 1;
            }
            int check = 0;
            var getCart = repositorycart.All();
            foreach (var c in getCart)
            {
                if (c.ProductId == cart.ProductId && c.AccountId == cart.AccountId)
                {
                    cart._id = c._id;
                    cart.Quantity += c.Quantity;
                    cart.TotalPrice = cart.Quantity * cart.TotalPrice;
                    repositorycart.Update(cart);
                    check++;
                }
                else
                {
                    continue;
                }
            }

            if (check == 0)
            {
                repositorycart.Insert(cart);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int CartId, Cart cart)
        {
            try
            {
                if (cart.Quantity < 1)
                {
                    cart.Quantity = 1;
                }

                cart.TotalPrice = cart.Quantity * cart.TotalPrice;
                cart._id = CartId;
                repositorycart.Update(cart);
            }
            catch (Exception)
            {

                return NotFound();
            }
            return RedirectToAction(nameof(Index));

        }
        public IActionResult Delete(int id)
        {
            repositorycart.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

BMongo1/Controllers/OrderController.cs
using BMongo1.Models;
using BMongo1.Models.BusinessModels;
using BMongo1.Models.ModelsViews;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BMongo1.Controllers
{
    public class OrderController : Controller
    {
        IRepositoryAccount repositoryaccount;
        IRepositoryCategory repositorycategory;
        IRepositoryCart repositorycart;
        IRepositoryProduct repositoryproduct;
        IRepositoryOrder repositoryorder;
        IRepositoryOrderDetail repositoryorderoetail;

        public OrderController(IRepositoryAccount repositoryaccount, IRepositoryCategory repositorycategory, IRepositoryCart repositorycart, IRepositoryProduct repositoryproduct, IRepositoryOrder repositoryorder, IRepositoryOrderDetail repositoryorderoetail)
        {
            this.repositoryaccount = repositoryaccount;
            this.repositorycategory = repositorycategory;
            this.repositorycart = repositorycart;
            this.repositoryproduct = repositoryproduct;
            this.repositoryorder = repositoryorder;
            this.repositoryorderoetail = repositoryorderoetail;
        }
        public IActionResult Index()
        {
            var order = repositoryorder.GetAll();
            return View(order);
        }

        public IActionResult Create()
        {
            var cart = repositorycart.GetForeignKey((int)HttpContext.Session.GetInt32("LoginId"));
            int c = 0;
            int a = 0;
            List<CartViewModel> list = new List<CartViewModel>();
            foreach (var item in cart)
            {
                if (item.AccountId == HttpContext.Session.GetInt32("LoginId"))
                {

                    c++;
                    ViewData["Number_Pro"] = c;
                    a += (int)item.TotalPrice;
                    ViewData["Total_Cart"] = a.ToString("#,##0 $");

                }
                list.Add(new CartViewModel() { _id = item._id, TotalPrice = item.TotalPrice, Quantity = item.Quantity, ProductName = item.ProductName, ProductImage = item.ProductImage, Price = item.Price });

            }
            ViewData["cart"] = list;

            return View();
        }

        // POST: Order/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Orders orders)
        {
            if (ModelState.IsValid)
            {
                orders.OrderStatus = "Confirming";
                orders.AccountId = HttpContext.Session.GetInt32("LoginId");
                repositoryorder.Insert(orders);
                //var check = true;
                //do
                //{
                var getCart = repositorycart.GetForeignKey((int)HttpContext.Session.GetInt32("LoginId"));

                //if (pro != null)
                //{
                foreach (var item in getCart)
                {
                    OrderDetail orderDetail = new OrderDetail();
                    orderDetail.Quantity = item.Quantity;
                    orderDetail.TotalPrice = item.TotalPrice;
                    orderDetail.ProductId = item.ProductId;
                    orderDetail.OrdersId = repositoryorder.GetId();

                    repositoryorderoetail.Insert(orderDetail);

                }
                repositorycart.DeleteAll((int)orders.AccountId);
                return RedirectToAction(nameof(Index));
            }

            var cart = repositorycart.GetForeignKey((int)HttpContext.Session.GetInt32("LoginId"));
            int c = 0;
            int a = 0;
            List<CartViewModel> list = new List<CartViewModel>();
            foreach (var item in cart)
            {
                if (item.AccountId == HttpContext.Session.GetInt32("LoginId"))
                {

                    c++;
                    ViewData["Number_Pro"] = c;
                    a += (int)item.TotalPrice;
                    ViewData["Total_Cart"] = a.ToString("#,##0 $");

                }
                list.Add(new CartViewModel() { _id = item._id, TotalPrice = item.TotalPrice, Quantity = item.Quantity, ProductName = item.ProductName, ProductImage = item.ProductImage, Price = item.Price });

            }
            ViewData["cart"] = list;
            return View(orders);
        }

    }
}

BMongo1/Controllers/OrderDetailsController.cs
using BMongo1.Models.BusinessModels;
using Microsoft.AspNetCore.Mvc;

namespace BMongo1.Controllers
{
    public class OrderDetailsController : Controller
    {
        IRepositoryAccount repositoryaccount;
        IRepositoryCategory repositorycategory;
        IRepositoryCart repositorycart;
        IRepositoryProduct repositoryproduct;
        IRepositoryOrder repositoryorder;
        IRepositoryOrderDetail repositoryorderoetail;

        public OrderDetailsController(IRepositoryAccount repositoryaccount, IRepositoryCategory repositorycategory, IRepositoryCart repositorycart, IRepositoryProduct repositoryproduct, IRepositoryOrder repositoryorder, IRepositoryOrderDetail repositoryorderoetail)
        {
            this.repositoryaccount = repositoryaccount;
            this.repositorycategory = repositorycategory;
            this.repositorycart = repositorycart;
            this.repositoryproduct = repositoryproduct;
            this.repositoryorder = repositoryorder;
            this.repositoryorderoetail = repositoryorderoetail;
        }
        public IActionResult Index(int id)
        {
            var ODT = repositoryorderoetail.GetForeignKey(id);
            return View(ODT);
        }
    }
}

BMongo1/Views/Order/Create.cshtml
@model BMongo1.Models.ModelsViews.OrdersViewModel
@using BMongo1.Models.ModelsViews
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Create";
}


<div class="hero-wrap hero-bread" style="background-image: url('/StyleUser/images//bg_1.jpg');">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Checkout</span></p>
                <h1 class="mb-0 bread">Checkout</h1>
            </div>
        </div>
    </div>
</div>

<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <table class="table">
                <thead class="thead-primary">
                    <tr class="text-center">
                        <th>&nbsp;</th>
                        <th>Product name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var galList = ViewData["cart"] as List<CartViewModel>;
                    }
                    @foreach (var item in galList)
                    {
                        <tr class="text-center">
                            <td class="image-prod"><div class="img" style="background-image:url('/Images/@Html.DisplayFor(modelItem => item.ProductImage)');"></div></td>

                            <td class="product-name">
                                <h3>@Html.DisplayFor(modelItem => item.ProductName)</h3>
                            </td>

                            <td class="price">@Html.DisplayFor(modelItem => item.Price)</td>

                            <td class="quantity">@Html.DisplayFor(modelItem => item.Quantity)</td>

                            <td class="total">@Html.DisplayFor(modelItem => item.TotalPrice)</td>
                        </tr>
                        <!-- END TR-->
                    }
                </tbody>
            </table>
            <div class="col-xl-7 ftco-animate">
                <form asp-action="Create" asp-controller="Order" class="billing-form" id="myform">
                    <h3 class="mb-4 billing-heading">Billing Details</h3>

                    <div class="row align-items-end">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="firstname">Full Name</label>
                                <input asp-for="ReceiverName" class="form-control" value='@HttpContextAccessor.HttpContext.Session.GetString("LoginName")'>
                                <span asp-validation-for="ReceiverName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="w-100"></div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="streetaddress">Street Address</label>
                                <input asp-for="ReceiverAddress" type="text" class="form-control" value='@HttpContextAccessor.HttpContext.Session.GetString("LoginAddress")' placeholder="House number and street name">
                                <span asp-validation-for="ReceiverAddress" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="w-100"></div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="phone">Phone</label>
                                <input type="text" asp-for="ReceiverPhone" class="form-control" value='@HttpContextAccessor.HttpContext.Session.GetString("LoginPhone")' placeholder="">
                                <span asp-validation-for="ReceiverPhone" class="text-danger"></span>
                                <input type="hidden" asp-for="OrderDate" class="form-control" value='@DateTime.Now.ToString("MM/dd/yyyy")' placeholder="">
                            </div>
                        </div>
                        <div class="w-100"></div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="towncity">Note</label>
                                <textarea asp-for="Note" class="form-control" rows="5"></textarea>
                            </div>
                        </div>

                        <div class="w-100"></div>

                    </div>
                </form><!-- END -->
            </div>
            <div class="col-xl-5">
                <div class="row mt-5 pt-3">
                    <div class="col-md-12 d-flex mb-5">
                        <div class="cart-detail cart-total p-3 p-md-4">
                            <h3 class="billing-heading mb-4">Cart Total</h3>
                            <span>Number Products</span>
                            <span>@ViewData["Number_Pro"]</span>

                            <hr>
                            <p class="d-flex total-price">
                                <span>Total</span>
                                <span>@ViewData["Total_Cart"]</span>
                            </p>
                            <p><button onclick="submitForm()" class="btn btn-primary py-3 px-4">Place an order</button></p>

                        </div>
                    </div>

                </div>
            </div> <!-- .col-md-8 -->
        </div>
    </div>
</section> <!-- .section -->
<script>
    function submitForm() {
        document.getElementById('myform').submit();
    }
</script>

BMongo1/Views/Order/Index.cshtml
@model IEnumerable<BMongo1.Models.Orders>

@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "My Order";
}

<div class="hero-wrap hero-bread" style="background-image: url('/StyleUser/images/cart1.jpg');">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs"><span class="mr-2"><a href="#">Home</a></span> <span>Order</span></p>
                <h1 class="mb-0 bread">My Order</h1>
            </div>
        </div>
    </div>
</div>
<section class="ftco-section ftco-cart">
    <div class="container">
        <div class="row">
            <div class="col-md-12 ftco-animate">
                <div class="cart-list">
                    <table class="table">

                        <thead class="thead-primary">
                            <tr class="text-center">
                                <th>Receiver Name</th>
                                <th> Phone</th>
                                <th>Address</th>
                                <th>Note</th>
                                <th>Status</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                @if (HttpContextAccessor.HttpContext.Session.GetInt32("LoginId") == item.AccountId)
                                {
                                    <tr class="text-center">
                                        <td class="price">
                                            <h3>@Html.DisplayFor(modelItem => item.ReceiverName)</h3>
                                        </td>
                                        <td class="price">@Html.DisplayFor(modelItem => item.ReceiverPhone)</td>
                                        <td class="product-name">@Html.DisplayFor(modelItem => item.ReceiverAddress)</td>
                                        @if (item.Note == null || item.Note == "")
                                        {
                                            <td class="total">Not Note</td>

                                        }
                                        else
                                        {
                                            <td class="total">@Html.DisplayFor(modelItem => item.Note)</td>

                                        }
                                        <td class="total">@Html.DisplayFor(modelItem => item.OrderStatus)</td>
                                        <td> <a asp-action="Index" asp-controller="OrderDetails" asp-route-id="@item._id" class="btn btn-primary"> Details</a> </td>
                                    </tr>

                                    <!-- END TR-->
                                }
                            }
                        </tbody>

                    </table>
                </div>
                <br />

            </div>
        </div>
        <p><a asp-action="Index" asp-controller="Cart" class="btn btn-primary py-3 px-4">Back</a></p>
    </div>

</section>